<?php

declare(strict_types=1);

use Madbox99\FilamentFormBuilder\Filament\Resources\RegistrationForms\Schemas\Sections\DetailsSection;

it('slugifies the name on create', function (): void {
    expect(DetailsSection::autoGeneratedSlug('Hello World', 'create'))
        ->toBe('hello-world');
});

it('handles accented characters', function (): void {
    expect(DetailsSection::autoGeneratedSlug('Árvíztűrő tükörfúrógép', 'create'))
        ->toBe('arvizturo-tukorfurogep');
});

it('returns empty string when name is empty on create', function (): void {
    expect(DetailsSection::autoGeneratedSlug('', 'create'))->toBe('')
        ->and(DetailsSection::autoGeneratedSlug(null, 'create'))->toBe('');
});

it('does not auto-generate when editing an existing form', function (): void {
    expect(DetailsSection::autoGeneratedSlug('New Name', 'edit'))->toBeNull();
});

it('does not auto-generate for any non-create operation', function (): void {
    expect(DetailsSection::autoGeneratedSlug('X', 'view'))->toBeNull()
        ->and(DetailsSection::autoGeneratedSlug('X', ''))->toBeNull();
});
